### ISSUE TITLE
Authentication rejected: The DTLS handshake timed out since latest update of Gateway

### ISSUE THREAD

**Issue by cipher2k** [hemtjanst/tradfri-mqtt#15]
Hi,

I am running into this issue now since the latest update of Tradfri Gateway:

`
Authentication rejected
Error: The DTLS handshake timed out
    at normalizeReason (/usr/local/lib/node_modules/tradfri-mqtt/node_modules/node-coap-client/build/lib/DeferredPromise.js:6:16)
    at Promise.rej [as reject] (/usr/local/lib/node_modules/tradfri-mqtt/node_modules/node-coap-client/build/lib/DeferredPromise.js:14:34)
    at Socket.onError (/usr/local/lib/node_modules/tradfri-mqtt/node_modules/node-coap-client/build/CoapClient.js:1003:33)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at Socket.killConnection (/usr/local/lib/node_modules/tradfri-mqtt/node_modules/node-dtls-client/build/dtls.js:221:22)
    at Socket.expectHandshake (/usr/local/lib/node_modules/tradfri-mqtt/node_modules/node-dtls-client/build/dtls.js:138:22)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/tradfri-mqtt/node_modules/node-dtls-client/build/dtls.js:96:61)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
`

I am not sure if it is related with the firmware or just a coincidence. But it worked for quite a few weeks and today I cannot control tradfri via MQTT anymore. IKEA app access works fine.

**Comment by bonan** [comment]
Is it possible your Trådfri gateway got a new IP address when rebooting after the upgrade?

Check DHCP leases in your router and make sure they match what's set as gateway in tradfri-mqtt

**Comment by cipher2k** [comment]
I checked that already. My gateway has a reserved IP from DHCP server.

Still have no idea why it is not working anymore.

**Comment by cipher2k** [comment]
There is a workaround for this issue in the latest node-coap-client and node-dtls-client modules. I submitted a pull request to enable the workaround in tradfri-mqtt.

**Comment by bonan** [comment]
Thanks for researching the issue and submitting a fix.

I've merged your fix and released a new version, however I haven't been able to test the fix yet as I no longer use the Trådfri gateway.

**Comment by bonan** [comment]
Closing due to inactivity
Re-open the issue if it's still broken in the latest version

**Comment by olem10** [comment]
I have got the same issue as cipher2k. The updates to the coap/dtls client modules did not solve the problem for me.

Authentication rejected
Error: The DTLS handshake timed out
    at normalizeReason (/usr/local/lib/node_modules/tradfri-mqtt/node_modules/node-coap-client/build/lib/DeferredPromise.js:6:16)
    at Promise.rej [as reject] (/usr/local/lib/node_modules/tradfri-mqtt/node_modules/node-coap-client/build/lib/DeferredPromise.js:14:34)
    at Socket.onError (/usr/local/lib/node_modules/tradfri-mqtt/node_modules/node-coap-client/build/CoapClient.js:1013:33)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at Socket.killConnection (/usr/local/lib/node_modules/tradfri-mqtt/node_modules/node-dtls-client/build/dtls.js:227:22)
    at Socket.expectHandshake (/usr/local/lib/node_modules/tradfri-mqtt/node_modules/node-dtls-client/build/dtls.js:144:22)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/tradfri-mqtt/node_modules/node-dtls-client/build/dtls.js:102:61)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by Arnootjoo** [comment]
Same for me. The fix in the last build worked for me, but this error shows since the last Tradfri update:. Hub software version is 1.15.55. Hope there's a fix for this.

_Error discovering Trådfri endpoints Error: The DTLS handshake timed out
    at normalizeReason (/app/node_modules/node-coap-client/build/lib/DeferredPromise.js:6:16)
    at Promise.rej [as reject] (/app/node_modules/node-coap-client/build/lib/DeferredPromise.js:14:34)
    at Socket.onError (/app/node_modules/node-coap-client/build/CoapClient.js:1012:29)
    at Object.onceWrapper (node:events:514:26)
    at Socket.emit (node:events:394:28)
    at Socket.killConnection (/app/node_modules/node-dtls-client/build/dtls.js:227:22)
    at Socket.expectHandshake (/app/node_modules/node-dtls-client/build/dtls.js:144:22)
    at Timeout.<anonymous> (/app/node_modules/node-dtls-client/build/dtls.js:102:61)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)_
